apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-backend
  name: shop-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
      - image: ci-cd-docker.pkg.coding.net/eshop/release/eshop
        name: shop-backend
        ports:
        - containerPort: 3000
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
      imagePullSecrets:
      - name: coding-registry-cred-7942737