apiVersion: v1
kind: Service
metadata:
  labels:
  name: shop-backend-service
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
  selector:
    app: shop-backend
  type: LoadBalancer